### ISSUE TITLE
This is really good idea to make own game engine!

### ISSUE THREAD

**Issue by Imperat** [co-code/doodle-game-engine#2]
Hi, Wlad!
If you forgot me I can remember.
I'm Misha - We have gotten bachelor degree together by writing CG programms for our best teacher - Mironov S. Can you provide some roadmap or guide for new contributors? I'm really think that I can take good C and C++ experience by observing this. 
Thank you!

**Comment by wlad031** [comment]
Hello, Misha! 
Of course, I haven't forgotten you!

This project hasn't the roadmap yet. But I have troubles with implementing ThreadPool pattern on C++. You can try to write your own solution.

**Comment by Imperat** [comment]
I need to research this pattern.
Thank you a lot!

**Comment by wlad031** [comment]
https://en.wikipedia.org/wiki/Thread_pool
https://docs.oracle.com/javase/tutorial/essential/concurrency/pools.html

**Comment by nikitabelonogov** [comment]
Hi, @Imperat

**Comment by Imperat** [comment]
Hey, @nikitabelonogov. How is your feeling today?
